version: 1.0.{build}
branches:
  only:
    - master
environment: 
  git_personal_access_token:
    secure: 1adLwpqQ7ba9tvS5BSO2pCiPEbs95ywiv+k6fQWb5Rwl1YKhMhDrNuC/QPmyxaA6
before_build:
  - nuget restore
after_test:
  - deployToGitHub
build_script:
  - SET DEPLOYMENT_TEMP="%APPVEYOR_BUILD_FOLDER%\dist"
  - msbuild.exe "%APPVEYOR_BUILD_FOLDER%\Fifthweek.sln" /t:Clean /p:Configuration=Release
  - msbuild.exe "%APPVEYOR_BUILD_FOLDER%\Fifthweek.sln" /t:Clean /p:Configuration=Debug
  - msbuild.exe "%APPVEYOR_BUILD_FOLDER%\Fifthweek.sln" /t:Build /p:Configuration=Release
  - msbuild.exe "%APPVEYOR_BUILD_FOLDER%\Fifthweek.Api\Fifthweek.Api.csproj" /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="%DEPLOYMENT_TEMP%";AutoParameterizationWebConfigConnectionStrings=false;Configuration=Release /p:SolutionDir="%APPVEYOR_BUILD_FOLDER%\.\\"
