version: 1.0.{build}
branches:
  only:
    - master
environment: 
  git_personal_access_token:
    secure: 1adLwpqQ7ba9tvS5BSO2pCiPEbs95ywiv+k6fQWb5Rwl1YKhMhDrNuC/QPmyxaA6
before_build:
  - nuget restore
after_test:
  - deployToGitHub fifthweek-api-dist api-dist
  - deployToGitHub fifthweek-webjobs-dist webjobs-dist
build_script:
  - SET API_DEPLOYMENT_TEMP="%APPVEYOR_BUILD_FOLDER%\api-dist"
  - SET WEBJOBS_DEPLOYMENT_TEMP="%APPVEYOR_BUILD_FOLDER%\webjobs-dist\App_Data\jobs\continuous"
  - msbuild.exe "%APPVEYOR_BUILD_FOLDER%\Fifthweek.sln" /t:Clean /p:Configuration=Release
  - msbuild.exe "%APPVEYOR_BUILD_FOLDER%\Fifthweek.sln" /t:Clean /p:Configuration=Debug
  - msbuild.exe "%APPVEYOR_BUILD_FOLDER%\Fifthweek.sln" /t:Build /p:Configuration=Release
  - xcopy /e /h "%APPVEYOR_BUILD_FOLDER%\Fifthweek.WebJobs.Files\bin\Release" "%WEBJOBS_DEPLOYMENT_TEMP%\files\"
  - xcopy /e /h "%APPVEYOR_BUILD_FOLDER%\Fifthweek.WebJobs.Thumbnails\bin\Release" "%WEBJOBS_DEPLOYMENT_TEMP%\thumbnails\"
  - xcopy /e /h "%APPVEYOR_BUILD_FOLDER%\Fifthweek.WebJobs.GarbageCollection\bin\Release" "%WEBJOBS_DEPLOYMENT_TEMP%\garbage-collection\"
  - msbuild.exe "%APPVEYOR_BUILD_FOLDER%\Fifthweek.Api\Fifthweek.Api.csproj" /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="%API_DEPLOYMENT_TEMP%";AutoParameterizationWebConfigConnectionStrings=false;Configuration=Release /p:SolutionDir="%APPVEYOR_BUILD_FOLDER%\.\\"
notifications:
  - provider: Slack
    auth_token:
      secure: dNohNyk1tMZ49NhLGLccecFy+/1ha7FEQyO/IPjMjRvzuIcsTXTPSgk/x/d42YHb
    channel: services
